apiVersion: oda.tmforum.org/v1beta3
kind: Component
metadata:
  name: partymanagement
  namespace: components
  labels:
    oda.tmforum.org/componentName: partymanagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
    lablabee.io/challenge: "3"
spec:
  id: TMFC020
  name: PartyManagement
  functionalBlock: PartyManagement
  description: "Party Management ODA-Component - LabLabee Challenge 3"
  version: "1.0.0"
  status: specified
  publicationDate: "2024-01-01T00:00:00Z"
  maintainers:
    - name: LabLabee
      email: lab@lablabee.io
  owners:
    - name: LabLabee
      email: lab@lablabee.io

  coreFunction:
    exposedAPIs:
      - name: partymanagement
        specification:
          - https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-Party-v4.0.0.swagger.json
        implementation: partymanagement-api
        apitype: openapi
        path: /tmf-api/partyManagement/v4
        developerUI: /tmf-api/partyManagement/v4/docs
        port: 8080
    dependentAPIs: []

  managementFunction:
    exposedAPIs:
      - name: metrics
        specification:
          - https://openmetrics.io/
        apitype: prometheus
        implementation: partymanagement-api
        path: /partymanagement/metrics
        port: 8080

  securityFunction:
    controllerRole: Admin
    exposedAPIs:
      - name: partyrole
        specification:
          - https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
        implementation: partymanagement-api
        apitype: openapi
        path: /tmf-api/partyRoleManagement/v4
        developerUI: /tmf-api/partyRoleManagement/v4/docs
        port: 8080
