# ============================================================
#  LabLabee – Challenge 3: ODA Canvas
#  ODA Component: Party Management – TMF632 v4
#
#  Schema verified from live CRD:
#    coreFunction.properties: [ "dependentAPIs", "exposedAPIs" ]
# ============================================================

apiVersion: oda.tmforum.org/v1beta2
kind: Component
metadata:
  name: partymanagement
  namespace: canvas
  labels:
    oda.tmforum.org/componentName: partymanagement
    oda.tmforum.org/funtionalBlockName: PartyManagement
    lablabee.io/challenge: "3"
spec:
  name: PartyManagement
  functionalBlock: PartyManagement
  id: TMFC020
  status: specified
  version: "1.0.0"
  description: "Party Management ODA-Component – LabLabee Challenge 3"
  publicationDate: "2024-01-01T00:00:00Z"
  maintainers:
    - name: LabLabee
      email: lab@lablabee.io
  owners:
    - name: LabLabee
      email: lab@lablabee.io

  coreFunction:
    exposedAPIs:
      - name: partymanagement
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-Party-v4.0.0.swagger.json
        implementation: partymanagement-api
        apitype: openapi
        path: /partymanagement/tmf-api/partyManagement/v4
        developerUI: /partymanagement/tmf-api/partyManagement/v4/docs
        port: 8080
    dependentAPIs: []

  managementFunction:
    exposedAPIs:
      - name: metrics
        apitype: prometheus
        implementation: partymanagement-api
        path: /partymanagement/metrics
        port: 8080

  securityFunction:
    controllerRole: Admin
    exposedAPIs:
      - name: partyrole
        specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
        implementation: partymanagement-api
        apitype: openapi
        path: /partymanagement/tmf-api/partyRoleManagement/v4
        developerUI: /partymanagement/tmf-api/partyRoleManagement/v4/docs
        port: 8080
